# Generated by Django 5.2.7 on 2025-11-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('cpf', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField()),
                ('sus_card', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('blood_type', models.CharField(max_length=3, null=True)),
                ('dad', models.CharField(max_length=65, null=True)),
                ('mom', models.CharField(max_length=65, null=True)),
            ],
        ),
    ]
