# Generated by Django 5.2.7 on 2025-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_blood_type_alter_patient_dad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sus_card',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
